name: "Accessibility Issue Ticket"
description: "Create an accessibility issue ticket"
title: "[A11y]:"
labels: ["508/Accessibility", "508-defect-x"]
assignees: []
body:
- type: markdown
  attributes:
    value: "## Definition of done"
- type: markdown
  attributes:
    value: |
      1. Review and acknowledge feedback.
      1. Fix and/or document decisions made.
      1. Accessibility specialist will close ticket after reviewing documented decisions / validating fix."
- type: input
  id: contact
  attributes:
    label: Point of contact
    description: The person who wrote or is responsible for this ticket. Usually an a11y specialist.
  validations:
    required: true
- type: dropdown
  id: severity
  attributes:
    label: Severity level
    options:
      - 0, Launchblocker. Potentially Harmful. Must be fixed immediately.
      - 1, Launchblocker. Critical. Must be fixed before launch.
      - 2, Serious. Should be fixed in 1-2 sprints post-launch.
      - 3, Moderate. Should be fixed in 1-3 sprints post-launch.
      - 4, Minor. Consider fixing or exploring in 2-4 sprints post-launch.
  validations:
    required: true
- type: checkboxes
  id: type
  attributes:
    label: Type of issue
    description: You may select more than one.
    options:
      - label: Screenreader
      - label: Keyboard
      - label: Focus
      - label: Headings
      - label: Color
      - label: Zoom
      - label: Semantics
      - label: Axe-core
      - label: Something else
- type: textarea
  id: details
  attributes:
    label: Details
    description: "Describe the issue and what problem it's creating"
    value: |
      ...
    render: bash
  validations:
    required: true
- type: textarea
  id: repro
  attributes:
    label: Reproduction steps
    description: "How do you trigger this issue? Please walk us through it step by step."
    value: |
      1.
      2.
      3.
      ...
    render: bash
  validations:
    required: true
