name: "Accessibility Issue Ticket"
description: "Create an accessibility issue ticket"
title: "[A11y]:"
labels: ["508/Accessibility", "508-defect-x"]
assignees: []
body:
- type: markdown
  attributes:
    value: "## Feedback framework"
- type: markdown
  attributes:
    value: |
      - **❗️ Must** for if the feedback must be applied 
      - **⚠️ Should** if the feedback is best practice 
      - **✔️ Consider** for suggestions/enhancements 
- type: markdown
  attributes:
    value: "## Definition of done"
- type: markdown
  attributes:
    value: |
      1. Review and acknowledge feedback.
      1. Fix and/or document decisions made.
      1. Accessibility specialist will close ticket after reviewing documented decisions / validating fix."
- type: dropdown
  id: download
  attributes:
    label: Severity level
    options:
      - [508-defect-0 :exclamation: Launchblocker](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-0)
      - [508-defect-1 :exclamation: Launchblocker](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-1)
      - [508-defect-2](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-2)
      - [508-defect-3](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-3)
      - [508-defect-4](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-4)
  validations:
    required: true
