name: "Accessibility Issue Ticket"
description: "Create an accessibility issue ticket"
title: "[A11y]:"
labels: ["508/Accessibility", "508-defect-x"]
assignees: []
body:
- type: markdown
  attributes:
    value: "## Feedback framework"
- type: markdown
  attributes:
    value: |
      - **❗️ Must** for if the feedback must be applied 
      - **⚠️ Should** if the feedback is best practice 
      - **✔️ Consider** for suggestions/enhancements 
- type: markdown
  attributes:
    value: "## Definition of done"
- type: markdown
  attributes:
    value: |
      1. Review and acknowledge feedback.
      1. Fix and/or document decisions made.
      1. Accessibility specialist will close ticket after reviewing documented decisions / validating fix."
- type: dropdown
  id: download
  attributes:
    label: Severity level
    options:
      - 0, Launchblocker. Potentially Harmful. Must be fixed immediately.
      - 1, Launchblocker. Critical. Must be fixed before launch.
      - 2, Serious. Should be fixed in 1-2 sprints post-launch.
      - 3, Moderate. Should be fixed in 1-3 sprints post-launch.
      - 4, Minor. Consider fixing or exploring in 2-4 sprints post-launch.
  validations:
    required: true
