name: "Accessibility Support Ticket (CAIA)"
description: "Request accessibility support from the CAIA team"
title: "[CAIA A11y Request]: (Insert your request description here)"
labels: ["508/Accessibility, sitewide CAIA, sitewide accessibility"]
assignees: [coforma-terry]
body:
- type: markdown
  attributes:
    value: "## How might we support you?"
- type: markdown
  attributes:
    value: |
      We offer the following accessibility support to VFS and platform teams:
      1. Accessibility maintenance audits
      1. Wireframe and mockup accessibility design reviews and annotations
      1. Support for research with disabled Veterans using assistive technologies
      1. [Workshops on how to conduct foundational accessibility testing to prepare for a staging review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/prepare-for-an-accessibility-staging-review)
      1. Hands on office hours to answer accessibility questions, help resolve open accessibility issues, and more
- type: input
  id: type
  attributes:
    label: Auditor(s)
    description: The person or people conducting this audit
  validations:
    required: true
- type: markdown
  attributes:
    value: "## Coverage of Testing"
- type: checkboxes
  id: automated
  attributes:
    label: Automated
    options:
      - label: Run axe checks on every page or unique state (required)
      - label: Run WAVE on every page if time allows. WAVE is more visual than axe or axe-coconut, but offers some excellent ways to identify nested headings and HTML5 landmark tags.
- type: checkboxes
  id: manual
  attributes:
    label: Manual
    options:
      - label: Color contrast checks (recommend using whocanuse.com for beyond compliance reports)
      - label: Color blindness checks
      - label: Zoom layouts to 400% and inspect them for readability. If layouts break at 400%, I will start reducing them until they become stable, and log the zoom ratio when things started breaking.
      - label: Keyboard navigation
- type: checkboxes
  id: screenreader
  attributes:
    label: Screen Reader
    options:
      - label: Firefox and NVDA
      - label: Edge and JAWS
      - label: iOS Safari and VoiceOver (Mobile)
      - label: Safari and Voiceover (Desktop)
      - label: Chrome and Talkback
- type: markdown
  attributes:
    value: "## Staging URL and Credentials"
- type: input
  id: staging-link
  attributes:
    label: Staging or Production Link
    description: Consider linking to the first page of the tool or feature you're auditing 
- type: input
  id: prototypes
  attributes:
    label: Prototype Link
    description: Provide a link to any relevant prototypes
- type: textarea
  id: testusers
  attributes:
    label: Test Users
    description: Provide a list of test users and any relevant instructions
    value: |
      1.
      2.
      3.
      ...
    render: bash
- type: markdown
  attributes:
    value: "[Passwords for test users](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/a11y-audit.md#:~:text=user%2B%3F%3F%40gmail.com-,Passwords,-Footer)"
      
      
      
      
      
