name: "Accessibility Support Ticket (CAIA)"
description: "Request accessibility support from the CAIA team"
title: "[CAIA A11y Request]: (Insert your request description here)"
labels: ["508/Accessibility, sitewide CAIA, sitewide accessibility"]
assignees: [coforma-terry]
body:
- type: markdown
  attributes:
    value: "## How might we support you?"
- type: markdown
  attributes:
    value: |
      We offer the following accessibility support to VFS and platform teams:
      1. Accessibility maintenance audits
      2. Wireframe and mockup accessibility design reviews and annotations
      3. Support for research with disabled Veterans using assistive technologies
      4. [Workshops on how to conduct foundational accessibility testing to prepare for a staging review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/prepare-for-an-accessibility-staging-review)
      5. Hands on office hours to answer accessibility questions, help resolve open accessibility issues, and more
- type: dropdown
  id: support-type
  attributes:
    label: What kind of support are you looking for?
    options: 
      - Maintenance audit
      - Design reviews and annotations
      - Research support
      - Foundational testing tutorial
      - Hands on office hours
      - Something else
  validations:
    required: true
- type: textarea
  id: something-else
  attributes:
    label: If something else, what do you need support with?
    value: |
      ...
    render: bash
  validations:
    required: false  
- type: input
  id: date
  attributes:
    label: When do you need this support by?
    description: This helps us prioritize requests as they come in 
  validations:
    required: true
- type: dropdown
  id: urgency
  attributes:
    label: How urgent is this request?
    options:
      - Very urgent e.g. actively blocking the launch of a product or causing harm to Veterans
      - Urgent e.g. we need this ASAP, but it's not blocking any work or causing harm
      - Not urgent, can be addresed when time allows
  validations:
    required: true
- type: textarea
  id: artifacts
  attributes:
    label: Supporting artifacts
    description: If relevant, please provide supporting artifacts as available
    value: |
      Link to product outline:
      Link to or attach user flows:
      Link to prototype or mockups:
      Link to any epics/issues that may be helpful:
      ...
    render: bash
  validations:
    required: true
- type: textarea
  id: team
  attributes:
    label: Tell us about your team
    description: This will help us reach out to you if needed
    value: |
      Team name:
      OCTO-DE product owner:
      Product manager:
      Designer:
      FE engineer:
      Product/team Slack channel:
      ...
    render: bash
  validations:
    required: true
- type: input
  id: champion
  attributes:
    label: Do you have an accessibility champion on your team?
    description: This is anyone who has gone [through our a11ychamps program](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsa/accessibility/a11y-champs) or has been recognized by the accessibility practice for their stewardship. If yes, let us know who below.
  validations:
    required: true
- type: markdown
  attributes:
    value: "## Next steps"
- type: markdown
  attributes:
    value: |
      Once you’ve submitted this ticket, please post a link to this issue in the #accessibility-help Slack channel and tag Terry Nichols.
      
      
