name: Documentation Support Request
description: Use this template to request documentation support from the Platform content team
title: Documentation support
labels: ['documentation-support']
body:
  - type: checkboxes
    id: help-type
    attributes:
      label: Request type
      description: What type of help do you need? (Check all that apply.)
      options: 
        - Writing new documentation
        - Updating previously published documentation
        - Reviewing recently written, never-before-published drafts
    validations:
      required: true
  - type: input
    id: number-of-docs
    attributes:
      label: How many documents to be created, updated, or reviewed?
  - type: input
    id: point-of-contact
    attributes:
      label: Who is the point of contact for this documentation?
  - type: input
    id: approvals
    attributes:
      label: Does this documentation require approval from anyone other than the point of contact before publishing? If so, who must approve?
  - type: checkboxes
    id: embedded media
    attributes:
      label: Do the documents contain embedded media? (Check all that apply.)
      description: Do the documents contain embedded media?
      options:
        - Screenshot(s)
        - Diagram (s)
        - Video (s)
  - type: checkboxes
    id: audience 
    attributes:
      label: Who are the primary users of this documentation? (Check all that apply.)
      description: Who are the primary users of this documentation?
      options: 
        - Developers
        - Designers and researchers
        - Product managers
        - Other
  - type:textarea
    id: Anything else?
    attributes:
      label: Links? References? Anything that will give us more context? Tip: Attach images or files by clicking this area to highlight it and then dragging files in.
