name: Documentation Support Request
description: Use this template to request documentation support from the Platform content team
title: Documentation support
labels: ['documentation-support']
body:
  - type: dropdown
    id: help-type
    attributes:
      label: What do you need help with?
      description: What do you need help with?
      options: 
        - Creating new documentation
        - Updating previously published documentation
        - Reviewing recently written, never before published drafts
    validations:
      required: true
  - type: checkboxes
    id: primary-users
    attributes:
      label: Who are the primary users of this documentation?
      description: Check all that apply.
      options: 
        - label: Developers
        - label: Designers and researchers
        - label: Product managers
        - label: Others
  - type: input
    id: number-of-docs
    attributes:
      label: Estimate the number of pages to be created, updated, or reviewed.
  - type: input
    id: point-of-contact
    attributes:
      label: Who is the point of contact for this documentation?
  - type: checkboxes
    id: plans-to-update
    attributes:
      label: Are there plans to update other documents/pages that have similar content?
      description: Check Yes or No.
      options: 
        - label: Yes
        - label: No
     
