name: "Monitoring Framework"
description: "Follow this framework for mature, proven application monitoring"
title: "[Monitoring Framework]: "
labels: ["Monitoring"]
assignees: []
body:
- type: markdown
  attributes:
    value: "## Details and Definition of done"
- type: markdown
  attributes:
    value: |
      1. Dashboards set up
      2. Link made available to people
- type: input
  id: teamName
  attributes:
    label: Team Name
  validations:
    required: true
- type: markdown
  attributes:
    value: "## Feature Endpoints"
- type: textarea
  id: endpoints
  attributes:
    label: Feature Endpoints
- type: checkboxes
  id: checklist
  attributes:
    label: Checklist
    options:
      - label: Dashboard created
      - label: Things done
      - label: Stuff accomplished
      - label: Celebrations ensued

      
      
