name: "Monitoring Framework"
description: "A recommended approach to robust monitoring/logging"
title: "[Monitoring Framework]: "
labels: ["Monitoring"]
assignees: []
body:
- type: markdown
  attributes:
    value: "## Details and Definition of done"
- type: markdown
  attrubtes:
    value: |
      This issue template will help walk you through a recommended approach to logging and monitoring and will generate a testing artifact you can submit as part of your staging review. Try to resolve as many issues as you're able to before your staging review, and update this artifact with that progress. Anything you're not able to resolve on your own can be discussed as part of the staging review.

      It's okay if you can't complete all of the steps, or if you identify problems but aren't able to fix them. Try to do as much as you can. Tell us what you're able to do, what you found, and if you have any questions or concerns heading into your review.

      For information on how to set up logging and monitoring, check out the [logging and monitoring guide] (Links to section in this document titled Setting up logging and monitoring).
- type: markdown
  attributes:
    value: |
      1. Dashboards set up
      2. Link made available to people
- type: input
  id: teamName
  attributes:
    label: Team Name
  validations:
    required: true
- type: markdown
  attributes:
    value: "## Feature Endpoints"
- type: textarea
  id: endpoints
  attributes:
    label: Feature Endpoints
- type: checkboxes
  id: checklist
  attributes:
    label: Checklist
    options:
      - label: Dashboard created
      - label: Things done
      - label: Stuff accomplished
      - label: Celebrations ensued

      
      
