name: "Monitoring Framework"
description: "A recommended approach to robust monitoring/logging"
title: "[Monitoring Framework]: "
labels: ["Monitoring"]
assignees: []
body:
- type: markdown
  attributes:
    value: |
      ## Description
      This issue template will help walk you through a recommended approach to logging and monitoring and will generate a testing artifact you can submit as part of your staging review. Try to resolve as many issues as you're able to before your staging review, and update this artifact with that progress. Anything you're not able to resolve on your own can be discussed as part of the staging review.

      It's okay if you can't complete all of the steps, or if you identify problems but aren't able to fix them. Try to do as much as you can. Tell us what you're able to do, what you found, and if you have any questions or concerns heading into your review.

      For information on how to set up logging and monitoring, check out the [logging and monitoring guide] (Links to section in this document titled Setting up logging and monitoring).
- type: markdown
  attributes:
    value: |
      1. Dashboards set up
      2. Link made available to people
- type: input
  id: teamName
  attributes:
    label: Team Name
  validations:
  required: true
- type: input
  id: productName
  attributes:
    label: Product Name
  validations:
    required: true
- type: markdown
  attributes:
    value: "## Feature Endpoints"
- type: textarea
  id: currentEndpoints
  attributes:
    label: Existing Endpoints
- type: textarea
  id: newEndpoints
  attributes:
    label: New Endpoints
- type: markdown
  attributes:
    value: "## Logging"
- type: markdown
  attributes:
    value: |
      ### Logged Data
      
      Here are some links to log messages that show best practices
      - [Concise](#)
      - [Complete](#)
      - [Traceable](#)
- type: textarea
  id: loggedData
  attributes:
    label: Logged Data
    description: What type of data do you log? Why?
- type: markdown
  attributes:
    value: |
      ### Capturing Sufficient Information
      It is important for all logging and monitoring to capture enough
      information that any team can read the logs and be able to take
      the necessary actions to remedy the issue. Logs should _NOT_ capture
      PII or other sensitive information.
- type: checkboxes
  id: sufficientLoggingChecklist
  attributes:
    label: Checklist
    options:
      - label: All logs have enough information to troubleshoot issues
      - label: All logs have enough information to tie an entire end-to-end transaction together
      - label: All logs have enough information to tie back to any database records
      - label: All logs are sanitized of any PII that would otherwise be captured
- type: textarea
  id: confidence
  attributes:
    label: Confidence in Logs
    description: Estimate the confidence you have in your logging solution from 1 (low) - 10 (high). What made you choose that number?
- type: markdown
  attributes:
    value: "## Troubleshooting"
- type: textarea
  id: method
  attributes:
    label: Troubleshooting method
    description: |
      Explain your process for troubleshooting issues that arise. Include information
      about how you would come to realize there's an issue, and what features of your
      logging and monitoring solution you could leverage to address the issue quickly.
- type: textarea
  id: firstToKnow
  attributes:
    label: First To Know
    description: What allows your team to be the first to know when there's an incident in your application?
- type: markdown
  attributes:
    value: "## External Services"
- type: textarea
  id: externalServices
  attributes:
    label: Downstream Service Integration
    description: |
      Most VA.gov features use downstream services in some capacity. If they are experiencing degraded states, 
      we should be the first to know about how our apps are impacted.
- type: checkboxes
  id: externalServicesChecklist
  attributes:
    label: Checklist
    options:
      - label: All external call (failures and successes) are logged with pertinent information
      - label: All external calls are logged with StatsD counters and/or a Sentry tag
- type: textarea
  id: consistency
  attributes:
    label: How do you know if your services are working?
- type: textarea
  id: rateTracking
  attributes:
    label: How do you track failures and successes over time?
- type: textarea
  id: missingFeatures
  attributes:
    label: Is there anything missing from your monitoring/logging/alerting solution?
    description: This could include access to certain tooling, integrations, or pie-in-the-sky ideas.
- type: textarea
  id: other
  attributes:
    label: What other questions do you have for the Platform team?

