name: OCTO-DE Crew Onboarding Checklist
description: Onboard a member of OCTO to a Digital Experience Crew
title: "[OCTO-DE Crew Onboarding]: "
labels: ["onboarding"]
body:
- type: dropdown
  id: crew_name
  attributes:
    label: What OCTO-DE Crew is the team member joining?
    multiple: false
    options:
      - Account Experience
      - Benefits
      - Health
      - Mobile
      - Platform
      - Sitewide
- type: input
  id: github_username
  attributes:
    label: Github Username
    description: What is the Github username of the person being onboarded?
    placeholder: '@octocat'
  validations:
    required: false
- type: checkboxes
  attributes:
    label: Has user been added to Department of Veterans Affairs Github Organization?
    description: User must be listed in https://github.com/orgs/department-of-veterans-affairs/people
    options:
    - label: User is member of Github org
      required: true
- type: checkboxes
  attributes:
    label: Crew Specific - Platform
    description: Onboarding tasks specific to OCTO-DE Platform Crew
    options:
    - label: "Update Team Roster (private) https://vfs.atlassian.net/wiki/spaces/OCLP/overview#Meet-the-team"
    - label: "Update Team Roster (public) https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623"
    - label: "Add to Slack group: @octo-de-platform"
    - label: "Add to Github group: octo-de-platform"
    - label: "Post welcome Slack message: #platform-team"
    - label: "Register for Platform Orientation: https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=governance-team&template=orientation-epic.md&title=Platform+Orientation+Template+%5BYour+name+here%5D"
      
      
      
      
      
      
      
