name: "Platform Feature Request"
description: "If you have a request for a feature you believe the VA Platform should implement, complete the information below."
title: "[Feature Request [Feature-Name]:"
labels:
  - "platform-feature-request"
assignees:
  - jchasia-adhoc  
body:
  - type: markdown
    attributes:
      value: |
        If you have a request for a feature you believe the VA Platform should implement, complete the information below. The more information Platform has, the faster we can process the request.
  - type: textarea
    id: topic
    attributes:
      label: Describe the problem
      description: "Describe the problem, and how solving this problem will make things better for VFS Teams, OCTO-DE, VA, or Content Editors."
      placeholder: 
    validations:
      required: true
  - type: textarea
    id: benefit
    attributes:
      label: Who will benefit 
      description: "How widespread is the problem, i.e. who do you believe would benefit from the Platform solving this problem?"
      placeholder: 
    validations:
      required: true
  - type: textarea
    id: Describe 
    attributes:
      label: Describe your idea
      description: "Describe your Platform feature or service idea, in other words describe how you think the Platform should solve this"
      placeholder: 
    validations:
      required: true
      description: "Provide the evidence that you have on the need for this enhancement"
      placeholder: 
    validations:
      required: true







  
