name: "Platform Feature Request"
description: "If you have a request for a feature you believe the VA Platform should implement, complete the information below."
title: "[Feature Request [Feature-Name]:"
labels:
  - "platform-feature-request"
assignees:
  - jchasia-adhoc
    
    
    
      
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this request!
  - type: input
    id: topic
    attributes:
      label: Topic
      description: What is the topic to discuss?
      placeholder: AWS network architecture
    validations:
      required: true
