labels:
  - "platform-architecture-working-group"
  - "Internal Request"
assignees:
  - f1337
  - thepipster
  - td-usds
  - mchelen-gov
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this request!
  - type: input
    id: topic
    attributes:
      label: Topic
      description: What is the topic to discuss?
      placeholder: AWS network architecture
    validations:
      required: true
