name: Recruitment Request (test)
description: File a recruitment request to Perigean
title: "[Recruitment Request]: Insert name of your study here"
labels: ["research"]
assignees:
  - joshkimux
body:
  - type: markdown
    attributes:
      value: |
        OCTO works with Perigean, a small business, to handle the recruitment, scheduling, and compensation of Veterans and caregivers. 
  - type: textarea
    id: ideal-session-count
    attributes:
      label: Ideally, how many participants do you want in your study?
      description: "Replace the 0s with the amount you want from each group"
      value: |
        Veterans: 0
        Family Members: 0
        Caregivers: 0
        Service Members: 0
        Total: (Add all the above)
    validations:
      required: true
  - type: dropdown
    id: equity-1
    attributes:
      label: Select your first primary equity category
      description: This ensures we're prioritizing the recruitment of underserved communities. If conducting usability testing, we strongly recommend testing with disabled Veterans first, ideally on a mobile device.
      multiple: true
      options:
        - LGBTQ+
        - Black
        - Native
        - Latina
        - 55+ years old
        - No college or higher education
        - Rural
        - Blind or low vision using a screen reader
        - Cognitive disabilities
        - Experiencing homelessness (custom request to Perigean)
        - Only has access to a mobile device (custom request to Perigean)
    validations:
      required: true
  - type: dropdown
    id: equity-2
    attributes:
      label: Select your second primary equity category
      description: Try and pick a category that is more relevant to your research topic.
      multiple: true
      options:
        - LGBTQ+
        - Black
        - Native
        - Latina
        - 55+ years old
        - No college or higher education
        - Rural
        - Blind or low vision using a screen reader
        - Cognitive disabilities
        - Experiencing homelessness (custom request to Perigean)
        - Only has access to a mobile device (custom request to Perigean)
    validations:
      required: true
