name: Easy Recruitment Request (test)
description: Use a simplified form to submit a recruitment request to Perigean. 
title: "[Recruitment Request]: Insert name of your study here"
labels: ["research"]
assignees:
  - joshkimux
body:
  - type: markdown
    attributes:
      value: |
        This is an easy request form that only uses primeria criteria. That means all the criteria selections below will apply to all your participants. 
        <br/> In other words, if you request for Black, Rural Veterans-- Perigean will aim to have every participant identify as a Black Veteran living in a rural location. If you want to submit a custom request and specify precise numbers for the demographics you're recruiting for, use our [custom form request instead](https://github.com/department-of-veterans-affairs/va.gov-research-repository/blob/master/research-plan-participant-criteria-update%202.md).
  - type: textarea
    id: ideal-session-count
    attributes:
      label: Ideally, how many participants do you want in your study?
      description: "Replace the 0s with the amount you want from each group. Perigean will recruit double your total ideal amount."
      value: |
        Veterans: 0
        Family Members: 0
        Caregivers: 0
        Service Members: 0
        Total: (Add all the above)
    validations:
      required: true
  - type: dropdown
    id: benefits-1
    attributes:
      label: What benefits or services should your participants have experience with?
      description: You can select "various" for a mix of all below or "no benefits" if you're looking for folk without experience. You can also select multiple if all your participants must have experience with multiple benefits.
      multiple: true
      options:
        - Various (a mix of all below)									
        - No Benefits or Service Experience										
        - Disability											
        - Education											
        - Employment											
        - Finances											
        - Healthcare											
        - Housing											
        - Life Insurance											
        - Memorialization											
        - Pension
  - type: dropdown
    id: branch
    attributes:
      label: What branch should your participants be affiliated with?
      options:
        - Various											
        - Marine Corps											
        - Army											
        - Navy											
        - Air Force											
        - Space Force											
        - Coast Guard											
        - National Guard											
        - Public Health Corps
  - type: dropdown
    id: technology
    attributes:
      label: What technology should the participant have experience with and use in the session?
      options:
        - Various											
        - Desktop											
        - Laptop											
        - Smartphone											
        - Tablet
  - type: dropdown
    id: website
    attributes:
      label: What websites should the participant have experience with in the past?
      options:
        - Various											
        - Authenticated experience with VA.gov (has an account)									
        - Unauthenticated experience with VA.gov (doesn't have an account)											
        - My Healthy Vet											
        - eBenefits
  - type: dropdown
    id: login
    attributes:
      label: What logins should the participant have experience with in the past?
      options:
        - Various											
        - DS Logon								
        - My Healthy Vet										
        - ID.me										
        - Login.gov
  - type: markdown
    attributes:
      value: "## Select up to 2 underrepresented groups as primary criteria"
  - type: markdown
    attributes:
      value: |
        Curious why we require this? [Check out our introduction to inclusive research.](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/accessibility/research/introduction.md) For the time being, we aim to limit requests to 2 as recruitment may become significantly delayed or difficult with too many required categories. 
  - type: dropdown
    id: equity-1
    attributes:
      label: First underrepresented group
      description: If conducting usability testing, we recommend starting with Veterans with cognitive disabilities or low vision / blind first using mobile devices. Covering more complex cases first will have better coverage than only testing with simple use cases.
      options:
        - LGBTQ+
        - Black
        - Native
        - Latina
        - 55+ years old
        - No college or higher education
        - Rural
        - Blind or low vision using a screen reader
        - Cognitive disabilities
        - Custom (use the open input field below)
        - Experiencing homelessness (custom request to Perigean)
        - Only has access to a mobile device (custom request to Perigean)
  - type: dropdown
    id: equity-2
    attributes:
      label: Second underrepresented group (optional, but recommended)
      description: We strongly recommend selecting a second category to account for intersectionality in your research.
      options:
        - LGBTQ+
        - Black
        - Native
        - Latina
        - 55+ years old
        - No college or higher education
        - Rural
        - Blind or low vision using a screen reader
        - Cognitive disabilities
        - Custom (use the open input field below)
        - Experiencing homelessness (custom request to Perigean)
        - Only has access to a mobile device (custom request to Perigean)
  - type: input
    id: equity-custom
    attributes:
      label: Use a custom equity category (up to 2 max)
      description: Not seeing a group you want to recruit? You can [reference this list of underserved communities based on the matrix of oppression](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/accessibility/research/introduction.md) or write in your own.
  - type: markdown
    attributes:
      value: |
        ## After submitting this ticket
        
        ### Your tasks
        - [ ] Add your team and study's labels to this ticket. This will help us track it in the research repo.
        - [ ] Once you know who will be on your team, fill out this roles form to inform us on who will be there. (need to create new form for this)
        
        ### What will happen next
        - Perigean will create a participant tracker in github for you to use (can we restrict access to protect PII or ask for them to scrub PII completely and use IDs instead?)
        - ?? [add 
        
        ### For the future
        - Spend some time thinking about which equity categories you selected to conduct research with. 
          - Why did you select those categories?
          - Which categories will you select next time?
          - If you present your research out in the future, use this template to share your reflection on inclusive research efforts
          - Need help? Reach out to the community and ask any questions at #inclusive-research
        
        
        
        
