name: Slack User Request
description: To request adjustments to users in dsva.slack.com
title: "[Slack]: "
labels: ["Slack Request"]
assignees:
  - eunicegar
  - LEHigley
body:
  - type: dropdown
    id: request_type
    attributes:
      label: Request Type
      description: What type of request are you making?
      options:
        - Add New User
        - Change User
    validations:
          required: true
  - type: textarea
    id: user_email
    attributes:
      label: Add New User: Email
      description: Email address of new user
      placeholder: user@example.com
  - type: textarea
    id: username
    attributes:
      label: Change User: Username
      description: Slack username of the existing user
      placeholder: @username
  - type: dropdown
    id: change_type
    attributes:
      label: Change User: Type
      description: Type of user change
      options:
        - Single channel guest to multi channel guest
        - Guest user to full member
  - type: textarea
    id: logs
    attributes:
      label: Guest Users: Channels
      description: What channels do they need to be added to? (For single or multi channel guests only)
      render: shell
