name: Application onboarding

on:
  issues:
    types:
      - opened

jobs:
  create-pr:
    if: contains(github.event.issue.title, 'Application to Onboard')
    runs-on: ubuntu-latest
    name: Onboard Application
    steps:
      - uses: actions/checkout@v2
      - uses: stefanbuck/github-issue-parser@v2
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/application-onboarding.yml
      
      - name: Check out ArgoCD infra repo
        uses: actions/checkout@v2
        with:
          repository: department-of-veterans-affairs/vsp-infra-argocd
          token: ${{ secrets.VA_VSP_BOT_GITHUB_TOKEN }}
          path: vsp-infra-argocd
          
      - name: Capture application name
        id: get_name
        run: |
          application_name=$(echo '${{ steps.issue-parser.outputs.jsonString }}' | jq -r '.appname')
          echo "::set-output name=application_name::$(echo ${application_name})"
          
      - name: Check if application already exists
        id: exists
        run: |
          application_exists=$(cat vsp-infra-argocd/chart/values.yaml | yq -o=json | jq -e '.projects|any(.name == "${{ steps.get_name.outputs.application_name }}")' || true)
          echo "::set-output name=application_exists::$(echo ${application_exists})"
        
      - name: If application exists
        if: steps.exists.outputs.application_exists == 'true'
        uses: KeisukeYamashita/create-comment@v1
        with:
          token: ${{ secrets.VA_VSP_BOT_GITHUB_TOKEN }}
          comment: |
            ${{ steps.get_name.outputs.application_name }} is already deployed to dev as defined
            in the `projects` here https://github.com/department-of-veterans-affairs/vsp-infra-argocd/blob/main/chart/values.yaml
        
      - name: If application doesnt exist
        if: steps.exists.outputs.application_exists == 'false'
        run: |
          cd vsp-infra-argocd/chart
          yq -i '.projects += [{"name": "${{ steps.get_name.outputs.application_name }}", "environments": ["dev"]}]' values.yaml
          git add -A
          
      - name: Create Pull Request
        if: steps.exists.outputs.application_exists == 'false'
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          path: vsp-infra-argocd/chart
          token: ${{ secrets.VA_VSP_BOT_GITHUB_TOKEN }}
          add-paths: values.yaml
          commit-message: "Adding application ${{ steps.get_name.outputs.application_name }} to ArgoCD appProjects dev"
          
      - name: Check outputs
        if: ${{ steps.cpr.outputs.pull-request-number }}
        uses: KeisukeYamashita/create-comment@v1
        with:
          token: ${{ secrets.VA_VSP_BOT_GITHUB_TOKEN }}
          comment: |
            The following PR has been created for onboarding ${{ steps.get_name.outputs.application_name }} to the dev environment
            ${{ steps.cpr.outputs.pull-request-url }}
